### ISSUE TITLE
Error trying to enable plugin

### ISSUE THREAD

**Issue by tylercroberts** [jawslouis/Battlegrounds-Match-Data#6]
Currently when trying to enable plugin version 0.4.2 on HDT version 1.12.16 I get the following error:

```
Make sure you are using the latest version of the Plugin and HDT.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Tyler\AppData\Roaming\HearthstoneDeckTracker\Plugins\BattlegroundsMatchData\BattlegroundsMatchData.config'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at BattlegroundsMatchData.Config.save()
   at BattlegroundsMatchData.BgMatchDataPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 93
```

**Comment by jawslouis** [comment]
Please check that the folder `C:\Users\Tyler\AppData\Roaming\HearthstoneDeckTracker\Plugins\BattlegroundsMatchData` exists, and that there is a file `BattlegroundsMatchData.config` that is formatted the same as in the [wiki](https://github.com/jawslouis/Battlegrounds-Match-Data/wiki/Editing-the-Config-File)
