### ISSUE TITLE
can't load

### ISSUE THREAD

**Issue by giladts** [jawslouis/Battlegrounds-Match-Data#8]
yesterday I downloaded the plugin and it worked well.
now it fails to load, I'm using the latest version of the Plugin and HDT.

in logs i see this:

System.ArgumentException: Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at BattlegroundsMatchData.SpreadsheetConnector.Initialize(Config config)
   at BattlegroundsMatchData.BgMatchDataPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 93
16:25:51|Error|PluginWrapper.Load >> Battlegrounds Match Data:
System.ArgumentException: Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at BattlegroundsMatchData.SpreadsheetConnector.Initialize(Config config)
   at BattlegroundsMatchData.BgMatchDataPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 93
16:25:51|Info|PluginWrapper.IsEnabled >> Enabled Battlegrounds Match Data
16:26:12|Info|TrackerPlugins.ButtonOpenPluginsFolder_OnClick >> [Helper.TryOpenUrl] C:\Users\XXXXX\AppData\Roaming\HearthstoneDeckTracker\Plugins
16:26:28|Info|PluginWrapper.Load >> Loading Battlegrounds Match Data
16:26:28|Info|BgMatchData.OnLoad >> Loaded Plugin. CSV Location: C:\Users\XXXXX\AppData\Roaming\HearthstoneDeckTracker\BGMatchDataGames.csv
16:26:28|Info|SpreadsheetConnector.Initialize >> Connecting to Google
16:26:28|Info|ErrorManager.AddError >> New error: Error loading Plugin "Battlegrounds Match Data"
Make sure you are using the latest version of the Plugin and HDT.

**Comment by jawslouis** [comment]
It seems that you have the google spreadsheet upload turned on, and you have an invalid credential location in the settings. Make 
sure that it follows the same format as in https://github.com/jawslouis/Battlegrounds-Match-Data/wiki/Auto-upload-to-Google-Spreadsheet

Alternatively, you could also just turn off the google spreadsheet upload in the settings.
